document.write("<table width=\"805\" border=\"0\" height=\"184\">");
document.write("<tbody>");
document.write("<tr>");
document.write("<td> <img src=\"Images/nicolasloizou2.jpeg\" alt=\"Nicolas Loizou\"");
document.write("width=\"200\" height=\"200\"> <\/td>");
document.write("<td>");
document.write("<h1>Nicolas Loizou</h1>");
document.write("<b>Assistant Professor</b>");
document.write("<br>");
document.write("<a href=\"https://www.jhu.edu/\"> Johns Hopkins University<\/a> </b>");
document.write("<br>");
document.write("<br>");
document.write("<b>Contact info:</b><br>");
document.write("Johns Hopkins University,<br>");
document.write("Department of Applied Mathematics and Statistics, <br>");
document.write(" 3400 N. Charles Street, Baltimore, MD 21218.<br>");
document.write("E-mail: nloizou@jhu.edu <br>");
document.write("<br>");
document.write("&nbsp;");
document.write("<a href=\"https:\/\/scholar.google.com\/citations?user=mvDmzAQAAAAJ&hl=en\"><img src=\"Images/scholar.png\" alt=\"Google Scholar\" width=\"25\" border=\"0\" height=\"25\"> <\/a> &nbsp;");
document.write("<a href=\"https:\/\/dblp.org\/pid\/173\/4958.html\"><img src=\"Images/dblp.png\" alt=\"dblp\" border=\"0\" height=\"25\"> <\/a> &nbsp;");
document.write("<a href=\"https:\/\/www.semanticscholar.org\/author\/N.-Loizou\/1941365\"><img src=\"Images/semantic.png\" alt=\"Semantic Scholar\" width=\"25\" border=\"0\" height=\"25\"> <\/a> &nbsp;");
document.write("<a href=\"https:\/\/www.linkedin.com\/in\/nicolas-loizou-6a2561b0\/\"> <img src=\"Images\/linkedin.png\" alt=\"Linked In\" width=\"25\" border=\"0\" height=\"25\"><\/a> &nbsp;");
document.write("<a href=\"https:\/\/twitter.com\/NicLoizou\/\"> <img src=\"Images\/twitter.png\" alt=\"Twitter\"  border=\"0\" height=\"25\"><\/a><br>");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<\/tbody>");
document.write("<\/table>");
